### PR TITLE
feat: Add macro to wrap imports and handle passing the `ident`

### PR DESCRIPTION
**Pull request by willemneal**
This is the first part of #167, which will handle the refactor of the `STATE` global using `once_cell`.

This also refactors errors into their own file. Though it doesn't unify into a singe type as suggested by @FlrnFrmm.

### CODE REVIEW

**Comment by willemneal** [comment]
@FlrnFrmm and @cohix.  I will add the once cell changes in the other PR.

**Comment by willemneal** [comment]
@cohix Still interested?

**Comment by cohix** [comment]
@willemneal yes certainly, we're having a very busy week so I apologize for not getting to this sooner. I will take a look as soon as I'm able... product launch coming next week so we're swamped 🙂

**Comment by willemneal** [comment]
No worries, been busy myself too. Just checking in.

**Comment by cohix** [comment]
@willemneal I think it would make sense to set up a code review call with myself and @jagger27 so we can learn exactly what's going on in this PR (I don't want it to languish just because we aren't so experienced with Rust...)

Could you ping us in Discord to set something up?

**Comment by cohix** [comment]
Thanks for the chat today @willemneal , for anyone else watching, we decided not to merge this, as the `ident` that this is automating is on track to be removed when we switch over to `wi-bindgen` in the coming months.

Thanks for teaching me how all this works :D

**Comment by cohix** [comment]
Closing as we're taking another approach

**Pull request closed without merging**
